### ISSUE TITLE
`switch` docs in README use `match x = 4` syntax

### ISSUE THREAD

**Issue by Janiczek** [HigherOrderCO/bend#281]
The docs should probably be updated like
```diff
-match x = 4 {
+switch 4 {
```
or perhaps
```haskell
let x = 4
switch x {
  // ... use the x-1 syntax
}
```

**Comment by developedby** [comment]
Good catch. I'll be rewriting the documentation this week, I'll make sure to pay attention to this.

**Comment by bbb651** [comment]
I haven't tried the project yet, but I have to say it sounds really weird to have both `switch` and `match` as statements, when according to the [docs](https://github.com/HigherOrderCO/Bend/blob/main/docs/syntax.md) the entire different between them is `switch` only accepts numbers and `match` only accepts `Option/none`? especially with the strong python syntax where only `match` exists and seems more akin to Bend's `switch`...

**Comment by developedby** [comment]
`switch` is for pattern matching on native numbers, while `match` is for types defined with `type` or `object`.
They could of course share the same syntax, but since `match` needs to do a lot more than `switch` (it becomes a lambda-encoded pattern matching, binds the fields of the objects, does some default-case magic), we decided it was better to keep them as separate syntax to clearly show that they're different.
