### ISSUE TITLE
(Question) Why not a Rust-like language?

### ISSUE THREAD

**Issue by hardBSDk** [HigherOrderCO/Bend#379]

**Comment by developedby** [comment]
If you mean just the syntax, we chose a python-looking one because people seem to have an easier time with it in general.
Personally I prefer Rust syntax, but I've also molded my brain to be C-shaped over the course of 10-15 years

**Comment by developedby** [comment]
If you mean the functionality (the type system, the approach to compilation, the philosophy, etc), then there is no reason to make Rust when Rust already exist.
The team obviously likes rust, it's why we chose it to write the compiler

**Comment by hardBSDk** [comment]
@developedby By Rust, I mean the memory safety, thread safety, lack of NULLs and compiler suggestions to better algorithms.

**Comment by developedby** [comment]
Memory safety is not relevant here since users don't manage memory directly. You could say bend is memory safe, like javascript is for example.

Thread safety is not relevant since the whole point of bend is parallelism without needing explicit and manual parallelization primitives like threads.

Obviously we also dont have null pointers since we don't have pointers.

Your last point I don't really understand, sorry. The compiler in rust will 100% allow you to do really dumb algorithms and not suggest you anything.
