### ISSUE TITLE
Outdated `run` commands in GUIDE.md

### ISSUE THREAD

**Issue by developedby** [HigherOrderCO/Bend#691]
### Reproducing the behavior

In https://github.com/HigherOrderCO/Bend/pull/630 we changed the default runtime to be the HVM C. The readme was updated, but `GUIDE.md` was not, and it still has the wrong commands.

Where it mentions the rust runtime, the command should be `bend run-rs`. `bend run` is now an alias to `bend run-c`.

We should also have a look at the other documents to see if there's anything that still mentions the wrong commands.

### System Settings

Bend commit bd592ca33f5e9b8b7a467b3da63501b697536966

**Comment by thiagola92** [comment]
I'm confuse (just started reading README.md).  

This is the expected behavior, right?  
```
bend run    <file.bend> # uses the C interpreter by default (parallel)
bend run-rs <file.bend> # uses the Rust interpreter (sequential)
bend run-c  <file.bend> # uses the C interpreter (parallel)
bend run-cu <file.bend> # uses the CUDA interpreter (massively parallel)
```

So this needs to be updated, right?  
https://github.com/HigherOrderCO/Bend/blob/71fb68004e076b8dd1f6ae4bfd2dff7f995b46b1/README.md?plain=1#L120-L128  

This could be updated to "run-rs" avoid confusion but would require changing others place, right?  
https://github.com/HigherOrderCO/Bend/blob/71fb68004e076b8dd1f6ae4bfd2dff7f995b46b1/src/main.rs#L291-L296
