### ISSUE TITLE
IO/get_time not working

### ISSUE THREAD

**Issue by GitCat3** [HigherOrderCO/Bend#720]
### Reproducing the behavior

Run the following program using `bend run-c`:
```py
def rnd(n):
  with IO:
    timestamp <- IO/get_time()
    bend n, state=timestamp:
      when n != 0:
        state = state ^ (state << 13)
        state = state ^ (state >> 17)
        state = state ^ (state << 5)
        res = List/Cons(state % 100, fork(n - 1, state))
      else:
        res = List/Nil
    return wrap(res)
```
Expected output is a random list of numbers
Actual output is `λa (a IO/Done/tag IO/MAGIC [λc (c 0 (39, 81))])`

### System Settings

Example:
 - HVM: 2.0.22
 - Bend: 0.2.36
 - OS: Linux Mint 21.3 Cinnamon
 - CPU: Intel Core i5-8250U 
 - GPU: Intel UHD Graphics 620
 - Cuda Version N/A

**Comment by NoamDev** [comment]
It works when used like this:

```
def rnd(n):
  with IO:
    timestamp <- IO/get_time()
    bend n, state=timestamp:
      when n != 0:
        state = state ^ (state << 13)
        state = state ^ (state >> 17)
        state = state ^ (state << 5)
        res = List/Cons(state % 100, fork(n - 1, state))
      else:
        res = List/Nil
    return wrap(res)

def main:
  with IO:
    x <- rnd(5)
    return x
```

@developedby is this how it's supposed to be used?
I remember main should wrap x, but it doesn't work that way.

**Comment by GitCat3** [comment]
when I run the revised code I get `[λb (b 0 (29, 75)), λd (d 0 (66, 87)), λf (f 0 (84, 3)), λh (h 0 (83, 74)), λj (j 0 (32, 88))]`, what does this mean?

**Comment by developedby** [comment]
@NoamDev Yes, I just tested here and it works. If you don't wrap the return of `main` usually nothing breaks, you just can't type check it.

I still need to add some code to unwrap the final IO value coming from main so that it looks nicer.

@GitCat3 you're probably not running the latest version of Bend. Please try installing the developement version (clone/download the git repo and then `cargo install --path .`).

It's returning a list of `Result/Ok(timestamp)`. In the latest version of Bend we already unwrap the result for you since get_time should never fail.

**Comment by NoamDev** [comment]
You can also install it using `cargo install --git https://github.com/HigherOrderCO/bend`
